<?php
declare(strict_types=1);
namespace App\Services;
use App\Core\Database;use App\Repositories\{LiquiditySessionRepository,LiquidityTeamRepository,LiquidityPoolRepository,LiquidityRoundRepository,LiquidityActionRepository,LiquidityEventRepository};use DomainException;use PDO;
final class LiquidityPoolService{private PDO $pdo;private LiquiditySessionRepository $sessions;private LiquidityTeamRepository $teams;private LiquidityPoolRepository $pool;private LiquidityRoundRepository $rounds;private LiquidityActionRepository $actions;private LiquidityEventRepository $events;private const ACTIONS=['deposit_nft','withdraw_nft_btc','withdraw_nft_cash','buy_btc','sell_btc','sell_nft','sell_share','pass'];
public function __construct(?PDO $pdo=null){$this->pdo=$pdo??Database::connection();$this->sessions=new LiquiditySessionRepository($this->pdo);$this->teams=new LiquidityTeamRepository($this->pdo);$this->pool=new LiquidityPoolRepository($this->pdo);$this->rounds=new LiquidityRoundRepository($this->pdo);$this->actions=new LiquidityActionRepository($this->pdo);$this->events=new LiquidityEventRepository($this->pdo);} 
public function createSession($d,$by=null):array{$d['access_code']=$d['access_code']??strtoupper(substr(bin2hex(random_bytes(4)),0,8));$id=$this->sessions->create($d,$by);$this->pool->createInitialState($id);$this->rounds->createRound($id,1);$this->sessions->setStatus($id,'active');return $this->sessions->findById($id)??[];}
public function createTeam($sid,$name):array{$s=$this->mustSession((int)$sid);$id=$this->teams->create(['session_id'=>$s['id'],'name'=>$name,'login_code'=>strtoupper(substr(bin2hex(random_bytes(3)),0,6)),'cash_balance'=>$s['initial_cash'],'nft_balance'=>$s['initial_nfts']]);return $this->teams->findById($id)??[];}
public function loginTeam($access,$login):array{$s=$this->sessions->findByAccessCode($access);if(!$s)throw new DomainException('Sessão não encontrada.');$t=$this->teams->findByLoginCodeAndSession($login,(int)$s['id']);if(!$t)throw new DomainException('Equipe não encontrada.');return ['session'=>$s,'team'=>$t];}
private function mustSession(int $id):array{$s=$this->sessions->findById($id);if(!$s)throw new DomainException('Sessão não encontrada.');return $s;}
public function submitTeamAction($sid,$tid,$a,$q=1):void{$sid=(int)$sid;$tid=(int)$tid;$q=(float)$q;if(!in_array($a,self::ACTIONS,true))throw new DomainException('Ação inválida.');$s=$this->mustSession($sid);if($s['status']!=='active')throw new DomainException('Sessão inativa.');$t=$this->teams->findById($tid);$p=$this->pool->findBySessionId($sid);if(!$t||!$p||(int)$t['session_id']!==$sid)throw new DomainException('Equipe inválida.');$r=(int)$s['current_round'];if($this->actions->hasTeamActed($sid,$r,$tid))throw new DomainException('Equipe já agiu na rodada.');$cash=0;$btc=0;$nft=0;$share=0;$poolN=(int)$p['pool_nfts'];$tot=(int)$p['total_shares'];$msg='Você passou a vez.';
if($a==='deposit_nft'){if((int)$t['nft_balance']<1)throw new DomainException('Sem NFT.');$nft=-1;$btc=(float)$s['btc_deposit_reward'];$share=1;$poolN++;$tot++;$msg='Você entrou na piscina: depositou 1 NFT, recebeu 10 BTC e ganhou 1 cota.';}
if($a==='withdraw_nft_btc'){if((float)$t['btc_balance']<(float)$s['btc_withdraw_cost']||$poolN<1)throw new DomainException('Condição inválida.');$btc=-(float)$s['btc_withdraw_cost'];$nft=1;$poolN--;$msg='Você retirou 1 NFT da piscina usando BTC.';}
if($a==='withdraw_nft_cash'){if((float)$t['cash_balance']<(float)$s['cash_withdraw_cost']||$poolN<1)throw new DomainException('Condição inválida.');$cash=-(float)$s['cash_withdraw_cost'];$nft=1;$poolN--;$msg='Você retirou 1 NFT da piscina usando dinheiro.';}
if($a==='buy_btc'){if($q<=0)throw new DomainException('Quantidade inválida.');$cost=$q*(float)$s['btc_buy_price'];if((float)$t['cash_balance']<$cost)throw new DomainException('Caixa insuficiente.');$cash=-$cost;$btc=$q;$msg='Você comprou '.rtrim(rtrim(number_format($q,4,'.',''),'0'),'.').' BTC.';}
if($a==='sell_btc'){if($q<=0|| (float)$t['btc_balance']<$q)throw new DomainException('BTC insuficiente.');$btc=-$q;$cash=$q*(float)$s['btc_sell_price'];$msg='Você vendeu '.rtrim(rtrim(number_format($q,4,'.',''),'0'),'.').' BTC.';}
if($a==='sell_nft'){if((int)$t['nft_balance']<1)throw new DomainException('Sem NFT.');$nft=-1;$cash=(float)$s['nft_sell_price'];$msg='Você vendeu 1 NFT em mãos.';}
if($a==='sell_share'){if((int)$t['pool_shares']<1)throw new DomainException('Sem cota.');$share=-1;$cash=(float)$s['share_sell_price'];$tot--;$msg='Você vendeu 1 cota da piscina.';}
$this->pdo->beginTransaction();try{$this->teams->updateBalances($tid,(float)$t['cash_balance']+$cash,(float)$t['btc_balance']+$btc,(int)$t['nft_balance']+$nft,(int)$t['pool_shares']+$share);$this->pool->updateState($sid,$poolN,$tot,(float)$p['total_value'],(float)$p['yield_per_share'],$this->determinePoolStatus($poolN,$tot));$this->actions->create($sid,$r,$tid,$a,$q);$this->events->create($sid,$r,$tid,$a,$msg,$cash,$btc,$nft,$share);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
public function advanceRound($sid):array{$s=$this->mustSession((int)$sid);if($s['status']!=='active')throw new DomainException('Sessão inativa.');$round=(int)$s['current_round'];if($round>(int)$s['total_rounds'])throw new DomainException('Limite de rodadas atingido.');$this->pdo->beginTransaction();try{$this->rounds->closeRound((int)$sid,$round);$teams=$this->teams->getBySessionId((int)$sid);$pool=$this->pool->findBySessionId((int)$sid);$totalValue=(int)$pool['pool_nfts']*(float)$s['nft_pool_value'];$yieldTotal=$totalValue*(float)$s['pool_yield_rate'];$yieldPer=((int)$pool['total_shares']>0)?$yieldTotal/(int)$pool['total_shares']:0.0;foreach($teams as $t){$cash=(float)$t['cash_balance']-(float)$s['round_fee']+((int)$t['pool_shares']*$yieldPer);$this->teams->updateBalances((int)$t['id'],$cash,(float)$t['btc_balance'],(int)$t['nft_balance'],(int)$t['pool_shares']);}$this->pool->updateState((int)$sid,(int)$pool['pool_nfts'],(int)$pool['total_shares'],$totalValue,$yieldPer,$this->determinePoolStatus((int)$pool['pool_nfts'],(int)$pool['total_shares']));$this->events->create((int)$sid,$round,null,'round_closed','A rodada '.$round.' foi encerrada. A piscina distribuiu R$ '.number_format($yieldPer,2,',','.').' por cota.',0,0,0,0);if($round<(int)$s['total_rounds']){$this->sessions->incrementRound((int)$sid);$this->rounds->createRound((int)$sid,$round+1);} $this->pdo->commit();return ['message'=>$round<(int)$s['total_rounds']?'Rodada avançada.':'Última rodada encerrada.'];}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
public function calculatePartialScore($t,$s):float{return (float)$t['cash_balance']+((float)$t['btc_balance']*(float)$s['btc_sell_price'])+((int)$t['nft_balance']*(float)$s['nft_sell_price'])+((int)$t['pool_shares']*(float)$s['share_sell_price']);}
public function calculateFinalScore($t,$s):float{return $this->calculatePartialScore($t,$s);} public function closeSession($sid):void{$s=$this->mustSession((int)$sid);$teams=$this->teams->getBySessionId((int)$sid);foreach($teams as $t){$this->teams->updateFinalScore((int)$t['id'],$this->calculateFinalScore($t,$s));}$this->sessions->setStatus((int)$sid,'closed');$this->rounds->closeRound((int)$sid,(int)$s['current_round']);$this->events->create((int)$sid,(int)$s['current_round'],null,'session_closed','Sessão encerrada.',0,0,0,0);} public function updatePoolTotals($sid):void{} public function determinePoolStatus($n,$ts):string{
if($n<=0)return 'empty';
if($n===1)return 'tense';
if($n>=2 && $ts>=1)return 'stable';
if($n>=1 && $ts===0)return 'critical';
return 'collapsed';
}
public function getRanking($sid):array{$s=$this->mustSession((int)$sid);$teams=$this->teams->getBySessionId((int)$sid);foreach($teams as &$t){$t['score']=$this->calculatePartialScore($t,$s);}usort($teams,fn($a,$b)=>$b['score']<=>$a['score']);return $teams;} public function getProjectorState($sid):array{return ['session'=>$this->mustSession((int)$sid),'pool'=>$this->pool->findBySessionId((int)$sid),'ranking'=>$this->getRanking((int)$sid),'feed'=>$this->events->getRecentBySession((int)$sid,20)];}
}