<?php
declare(strict_types=1);
namespace App\Services;

use App\Core\Database;
use App\Repositories\{LiquiditySessionRepository,LiquidityTeamRepository,LiquidityPoolRepository,LiquidityRoundRepository,LiquidityActionRepository,LiquidityEventRepository};
use DomainException;
use PDO;

final class LiquidityPoolService {
    private PDO $pdo; private LiquiditySessionRepository $sessions; private LiquidityTeamRepository $teams; private LiquidityPoolRepository $pool; private LiquidityRoundRepository $rounds; private LiquidityActionRepository $actions; private LiquidityEventRepository $events;
    private const ACTIONS=['deposit_nft','withdraw_nft_btc','withdraw_nft_cash','buy_btc','sell_btc','sell_nft','sell_share','trade_nft_between_teams','pass'];
    public function __construct(?PDO $pdo=null){$this->pdo=$pdo??Database::connection();$this->sessions=new LiquiditySessionRepository($this->pdo);$this->teams=new LiquidityTeamRepository($this->pdo);$this->pool=new LiquidityPoolRepository($this->pdo);$this->rounds=new LiquidityRoundRepository($this->pdo);$this->actions=new LiquidityActionRepository($this->pdo);$this->events=new LiquidityEventRepository($this->pdo);} 
    public function createSession($d,$by=null):array{$d['access_code']=$d['access_code']??strtoupper(substr(bin2hex(random_bytes(4)),0,8));$id=$this->sessions->create($d,$by);$this->pool->createInitialState($id);$this->rounds->createRound($id,1);$this->sessions->setStatus($id,'active');return $this->sessions->findById($id)??[];}
    public function createTeam($sid,$name):array{$s=$this->mustSession((int)$sid);$id=$this->teams->create(['session_id'=>$s['id'],'name'=>$name,'login_code'=>strtoupper(substr(bin2hex(random_bytes(3)),0,6)),'cash_balance'=>$s['initial_cash'],'nft_balance'=>$s['initial_nfts']]);return $this->teams->findById($id)??[];}
    public function loginTeam($access,$login):array{$s=$this->sessions->findByAccessCode($access);if(!$s)throw new DomainException('Sessão não encontrada.');$t=$this->teams->findByLoginCodeAndSession($login,(int)$s['id']);if(!$t)throw new DomainException('Equipe não encontrada.');return ['session'=>$s,'team'=>$t];}
    private function mustSession(int $id):array{$s=$this->sessions->findById($id);if(!$s)throw new DomainException('Sessão não encontrada.');return $s;}

    public function submitTeamAction($sid,$tid,$a,$q=1,$extra=[]):void{
        $sid=(int)$sid;$tid=(int)$tid;$q=(float)$q;if(!in_array($a,self::ACTIONS,true))throw new DomainException('Ação inválida.');
        $s=$this->mustSession($sid); if(($s['status']??'')==='closed') throw new DomainException('Sessão encerrada.');
        $t=$this->teams->findById($tid); $p=$this->pool->findBySessionId($sid); if(!$t||!$p||(int)$t['session_id']!==$sid) throw new DomainException('Equipe inválida.');
        if((int)($t['is_eliminated']??0)===1) throw new DomainException('Equipe eliminada não pode agir.');
        $phase=(string)($s['session_phase']??'regular'); if(!in_array($phase,['regular','semifinal','final'],true)) throw new DomainException('Fase encerrada.');
        $r=(int)$s['current_round']; if($this->actions->hasTeamActed($sid,$r,$tid)) throw new DomainException('Equipe já agiu na rodada.');
        $result=['cash'=>0.0,'btc'=>0.0,'nft'=>0,'share'=>0,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares'],'msg'=>'Você passou a vez.'];
        if($a==='deposit_nft')$result=$this->depositNft($t,$s,$p);
        elseif($a==='withdraw_nft_btc')$result=$this->withdrawNftWithBtc($t,$s,$p);
        elseif($a==='withdraw_nft_cash')$result=$this->withdrawNftWithCash($t,$s,$p);
        elseif($a==='buy_btc')$result=$this->buyBtc($t,$s,$q,$p);
        elseif($a==='sell_btc')$result=$this->sellBtc($t,$s,$q,$p);
        elseif($a==='sell_nft')$result=$this->sellNft($t,$s,$p);
        elseif($a==='sell_share')$result=$this->sellShare($t,$s,$p);
        elseif($a==='trade_nft_between_teams')$result=$this->tradeNftBetweenTeams($sid,$tid,$t,$extra,$r,$p);
        else $result=$this->passTurn($p);

        $this->pdo->beginTransaction(); try {
            $this->teams->updateBalances($tid,(float)$t['cash_balance']+$result['cash'],(float)$t['btc_balance']+$result['btc'],(int)$t['nft_balance']+$result['nft'],(int)$t['pool_shares']+$result['share']);
            $this->pool->updateState($sid,$result['poolN'],$result['tot'],(float)$p['total_value'],(float)$p['yield_per_share'],$this->determinePoolStatus($result['poolN'],$result['tot']));
            $this->actions->create($sid,$r,$tid,$a,$q,$extra['target_team_id']??null,$extra['price']??null);
            $this->events->create($sid,$r,$tid,$a,$result['msg'],$result['cash'],$result['btc'],$result['nft'],$result['share']);
            $this->updatePoolTotals($sid); $this->pdo->commit();
        } catch(\Throwable $e){ if($this->pdo->inTransaction())$this->pdo->rollBack(); throw $e; }
    }
    public function depositNft($t,$s,$p):array{if((int)$t['nft_balance']<1)throw new DomainException('Sem NFT.');return ['cash'=>0,'btc'=>(float)$s['btc_deposit_reward'],'nft'=>-1,'share'=>1,'poolN'=>(int)$p['pool_nfts']+1,'tot'=>(int)$p['total_shares']+1,'msg'=>'Você entrega uma NFT ao organismo coletivo, recebe 10 BTC e ganha 1 cota.'];}
    public function withdrawNftWithBtc($t,$s,$p):array{if((float)$t['btc_balance']<(float)$s['btc_withdraw_cost']||(int)$p['pool_nfts']<1)throw new DomainException('Condição inválida.');return ['cash'=>0,'btc'=>-(float)$s['btc_withdraw_cost'],'nft'=>1,'share'=>0,'poolN'=>(int)$p['pool_nfts']-1,'tot'=>(int)$p['total_shares'],'msg'=>'Você recupera uma NFT, mas reduz a profundidade da piscina.'];}
    public function withdrawNftWithCash($t,$s,$p):array{if((float)$t['cash_balance']<(float)$s['cash_withdraw_cost']||(int)$p['pool_nfts']<1)throw new DomainException('Condição inválida.');return ['cash'=>-(float)$s['cash_withdraw_cost'],'btc'=>0,'nft'=>1,'share'=>0,'poolN'=>(int)$p['pool_nfts']-1,'tot'=>(int)$p['total_shares'],'msg'=>'Você recupera uma NFT, mas reduz a profundidade da piscina.'];}
    public function buyBtc($t,$s,$q,$p):array{if($q<=0)throw new DomainException('Quantidade inválida.');$cost=$q*(float)$s['btc_buy_price'];if((float)$t['cash_balance']<$cost)throw new DomainException('Caixa insuficiente.');return ['cash'=>-$cost,'btc'=>$q,'nft'=>0,'share'=>0,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares'],'msg'=>'Você troca caixa por poder de retirada.'];}
    public function sellBtc($t,$s,$q,$p):array{if($q<=0||(float)$t['btc_balance']<$q)throw new DomainException('BTC insuficiente.');return ['cash'=>$q*(float)$s['btc_sell_price'],'btc'=>-$q,'nft'=>0,'share'=>0,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares'],'msg'=>'Você transforma BTC em caixa imediato.'];}
    public function sellNft($t,$s,$p):array{if((int)$t['nft_balance']<1)throw new DomainException('Sem NFT.');return ['cash'=>(float)$s['nft_sell_price'],'btc'=>0,'nft'=>-1,'share'=>0,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares'],'msg'=>'Você vende a NFT que está fora da piscina e reforça o caixa.'];}
    public function sellShare($t,$s,$p):array{if((int)$t['pool_shares']<1)throw new DomainException('Sem cota.');return ['cash'=>(float)$s['share_sell_price'],'btc'=>0,'nft'=>0,'share'=>-1,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares']-1,'msg'=>'Você reduz sua participação no rendimento coletivo.'];}
    public function passTurn($p):array{return ['cash'=>0,'btc'=>0,'nft'=>0,'share'=>0,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares'],'msg'=>'Você observa o mercado sem se mover.'];}
    public function tradeNftBetweenTeams($sid,$tid,$buyer,$extra,$round,$p):array{ $target=(int)($extra['target_team_id']??0); $price=(float)($extra['price']??0); if($target<=0||$target===$tid||$price<=0)throw new DomainException('Dados de compra inválidos.'); $seller=$this->teams->findById($target); if(!$seller||(int)$seller['session_id']!==$sid)throw new DomainException('Equipe alvo inválida.'); if((float)$buyer['cash_balance']<$price)throw new DomainException('Caixa insuficiente.'); if((int)$seller['nft_balance']<1)throw new DomainException('Equipe vendedora sem NFT.'); $this->teams->updateBalances($target,(float)$seller['cash_balance']+$price,(float)$seller['btc_balance'],(int)$seller['nft_balance']-1,(int)$seller['pool_shares']); $this->events->create($sid,$round,$target,'trade_nft_sell','Equipe '.$buyer['name'].' comprou 1 NFT da Equipe '.$seller['name'].' por R$ '.number_format($price,2,',','.'),$price,0,-1,0); return ['cash'=>-$price,'btc'=>0,'nft'=>1,'share'=>0,'poolN'=>(int)$p['pool_nfts'],'tot'=>(int)$p['total_shares'],'msg'=>'Equipe '.$buyer['name'].' comprou 1 NFT da Equipe '.$seller['name'].' por R$ '.number_format($price,2,',','.')]; }

    public function advanceRound($sid):array{ $s=$this->mustSession((int)$sid); if(($s['status']??'')==='closed')throw new DomainException('Sessão encerrada.'); $round=(int)$s['current_round']; $this->pdo->beginTransaction(); try{ $this->rounds->closeRound((int)$sid,$round); $teams=$this->teams->getBySessionId((int)$sid); $pool=$this->pool->findBySessionId((int)$sid); $totalValue=(int)$pool['pool_nfts']*(float)$s['nft_pool_value']; $yieldTotal=$totalValue*(float)$s['pool_yield_rate']; $yieldPer=((int)$pool['total_shares']>0)?$yieldTotal/(int)$pool['total_shares']:0.0; foreach($teams as $t){$this->teams->updateBalances((int)$t['id'],(float)$t['cash_balance']-(float)$s['round_fee']+((int)$t['pool_shares']*$yieldPer),(float)$t['btc_balance'],(int)$t['nft_balance'],(int)$t['pool_shares']);} $this->pool->updateState((int)$sid,(int)$pool['pool_nfts'],(int)$pool['total_shares'],$totalValue,$yieldPer,$this->determinePoolStatus((int)$pool['pool_nfts'],(int)$pool['total_shares'])); $this->events->create((int)$sid,$round,null,'round_closed','Rodada '.$round.' encerrada. Cada time pagou R$ 100. A piscina distribuiu R$ '.number_format($yieldPer,2,',','.').' por cota.',0,0,0,0); if($round<(int)$s['total_rounds']){$this->sessions->incrementRound((int)$sid);$this->rounds->createRound((int)$sid,$round+1);} $this->pdo->commit(); return ['message'=>'Rodada avançada.']; }catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    public function evaluateSemifinal($sid):void{$s=$this->mustSession((int)$sid);$teams=$this->teams->getBySessionId((int)$sid);foreach($teams as $t){$ok=(int)$t['nft_balance']>=1; $this->pdo->prepare('UPDATE liquidity_teams SET is_eliminated=?, qualified_for_final=?, updated_at=NOW() WHERE id=?')->execute([$ok?0:1,$ok?1:0,(int)$t['id']]); $this->events->create((int)$sid,(int)$s['current_round'],(int)$t['id'],'semifinal',($ok?'Classificada':'Eliminada').' na semifinal.',0,0,0,0);} $this->pdo->prepare("UPDATE liquidity_sessions SET session_phase='final', updated_at=NOW() WHERE id=?")->execute([(int)$sid]);}
    public function closeFinal($sid):void{$s=$this->mustSession((int)$sid);$teams=$this->teams->getBySessionId((int)$sid);usort($teams,fn($a,$b)=>(float)$b['cash_balance']<=>(float)$a['cash_balance']);$w=$teams[0]??null;foreach($teams as $t){$this->teams->updateFinalScore((int)$t['id'],(float)$t['cash_balance']);} if($w){$this->events->create((int)$sid,(int)$s['current_round'],(int)$w['id'],'final_winner','Equipe '.$w['name'].' venceu a final com R$ '.number_format((float)$w['cash_balance'],2,',','.'),0,0,0,0);} $this->pdo->prepare("UPDATE liquidity_sessions SET session_phase='closed', status='closed', updated_at=NOW() WHERE id=?")->execute([(int)$sid]);}
    public function calculatePartialScore($t,$s):float{return (float)$t['cash_balance']+((float)$t['btc_balance']*(float)$s['btc_sell_price'])+((int)$t['nft_balance']*(float)$s['nft_sell_price'])+((int)$t['pool_shares']*(float)$s['share_sell_price']);}
    public function calculateFinalCashScore($t):float{return (float)$t['cash_balance'];}
    public function getRanking($sid):array{$s=$this->mustSession((int)$sid);$teams=$this->teams->getBySessionId((int)$sid);foreach($teams as &$t){$t['score']=$this->calculatePartialScore($t,$s);$t['final_cash_score']=$this->calculateFinalCashScore($t);}usort($teams,fn($a,$b)=>$b['score']<=>$a['score']);return $teams;}
    public function updatePoolTotals($sid):void{$s=$this->mustSession((int)$sid);$p=$this->pool->findBySessionId((int)$sid);$total=(int)$p['pool_nfts']*(float)$s['nft_pool_value'];$yield=((int)$p['total_shares']>0)?($total*(float)$s['pool_yield_rate'])/(int)$p['total_shares']:0;$this->pool->updateState((int)$sid,(int)$p['pool_nfts'],(int)$p['total_shares'],$total,$yield,$this->determinePoolStatus((int)$p['pool_nfts'],(int)$p['total_shares']));}
    public function updatePoolStatus($sid):void{$this->updatePoolTotals($sid);} public function determinePoolStatus($n,$ts):string{if($n<=0)return 'empty';if($n===1)return 'tense';if($n>=2 && $ts>=1)return 'stable';if($n>=1 && $ts===0)return 'critical';return 'collapsed';}
    public function closeSession($sid):void{$this->closeFinal($sid);} public function getProjectorState($sid):array{return ['session'=>$this->mustSession((int)$sid),'pool'=>$this->pool->findBySessionId((int)$sid),'ranking'=>$this->getRanking((int)$sid),'feed'=>$this->events->getRecentBySession((int)$sid,20)];}
}
