<?php declare(strict_types=1);
namespace App\Repositories;
use App\Core\Database; use PDO;
final class LiquidityTradeProposalRepository{private PDO $pdo; public function __construct(?PDO $pdo=null){$this->pdo=$pdo??Database::connection();}
 public function create(array $d):int{$st=$this->pdo->prepare('INSERT INTO liquidity_trade_proposals (game_id,round_number,proposer_team_id,counterparty_team_id,proposer_user_id,action_type,asset_type,quantity,unit_price,total_price,status,proposer_approved_at,master_approved_at,executed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute([(int)$d['game_id'],(int)$d['round_number'],(int)$d['proposer_team_id'],(int)$d['counterparty_team_id'],$d['proposer_user_id']??null,$d['action_type'],$d['asset_type'],(float)$d['quantity'],(float)$d['unit_price'],(float)$d['total_price'],$d['status']??'pending_counterparty',$d['proposer_approved_at']??date('Y-m-d H:i:s'),$d['master_approved_at']??null,$d['executed_at']??null]);return (int)$this->pdo->lastInsertId();}
 public function findInGame(int $gameId,int $id):?array{$st=$this->pdo->prepare('SELECT * FROM liquidity_trade_proposals WHERE game_id=? AND id=? LIMIT 1');$st->execute([$gameId,$id]);$r=$st->fetch();return $r?:null;}
 public function sent(int $gameId,int $teamId):array{$st=$this->pdo->prepare('SELECT p.*, t.name counterparty_name FROM liquidity_trade_proposals p JOIN liquidity_teams t ON t.id=p.counterparty_team_id WHERE p.game_id=? AND p.proposer_team_id=? ORDER BY p.id DESC');$st->execute([$gameId,$teamId]);return $st->fetchAll();}
 public function received(int $gameId,int $teamId):array{$st=$this->pdo->prepare('SELECT p.*, t.name proposer_name FROM liquidity_trade_proposals p JOIN liquidity_teams t ON t.id=p.proposer_team_id WHERE p.game_id=? AND p.counterparty_team_id=? ORDER BY p.id DESC');$st->execute([$gameId,$teamId]);return $st->fetchAll();}
 public function history(int $gameId,int $teamId):array{$st=$this->pdo->prepare("SELECT p.*, pt.name proposer_name, ct.name counterparty_name FROM liquidity_trade_proposals p JOIN liquidity_teams pt ON pt.id=p.proposer_team_id JOIN liquidity_teams ct ON ct.id=p.counterparty_team_id WHERE p.game_id=? AND (p.proposer_team_id=? OR p.counterparty_team_id=?) AND p.status IN ('executed','rejected','cancelled','master_executed') ORDER BY p.id DESC LIMIT 50");$st->execute([$gameId,$teamId,$teamId]);return $st->fetchAll();}
 public function publicHistory(int $gameId,int $limit=12):array{$limit=max(1,min(50,$limit));$st=$this->pdo->prepare("SELECT p.*, pt.name proposer_name, ct.name counterparty_name FROM liquidity_trade_proposals p JOIN liquidity_teams pt ON pt.id=p.proposer_team_id JOIN liquidity_teams ct ON ct.id=p.counterparty_team_id WHERE p.game_id=? AND p.status IN ('executed','rejected','cancelled','master_executed') ORDER BY p.id DESC LIMIT ".$limit);$st->execute([$gameId]);return $st->fetchAll();}
}
